In [22]:
# importing al the necessary libraries in this cell
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score,classification_report
from sklearn.preprocessing import StandardScaler,PowerTransformer
from sklearn.decomposition import PCA
from xgboost import XGBClassifier

warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv('processed data/clustered_data.csv')
df.shape

(2240, 22)

In [27]:
df_copy = df.copy()

In [8]:
df.head(3)

,Age,Education,Marital Status,Parental Status,Children,Income,Total_Spending,Days_as_Customer,Recency,Wines,...,Fish,Sweets,Gold,Web,Catalog,Store,Discount Purchases,Total Promo,NumWebVisitsMonth,cluster
0,65,2,0,0,0,58138.0,1617.0,5053.0,58,635,...,120.5,81,88.0,8,10,4,3,0,7,0
1,68,2,0,1,2,46344.0,27.0,4503.0,38,11,...,2.0,1,6.0,1,1,2,2,0,5,2
2,57,2,1,0,0,71613.0,776.0,4702.0,26,426,...,111.0,21,42.0,8,2,10,1,0,4,0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 2240 non-null   int64
 1   Education           2240 non-null   int64
 2   Marital Status      2240 non-null   int64
 3   Parental Status     2240 non-null   int64
 4   Children            2240 non-null   int64
 5   Income              2240 non-null   float64
 6   Total_Spending      2240 non-null   float64
 7   Days_as_Customer    2240 non-null   float64
 8   Recency             2240 non-null   int64
 9   Wines               2240 non-null   int64
 10  Fruits              2240 non-null   int64
 11  Meat                2240 non-null   int64
 12  Fish                2240 non-null   float64
 13  Sweets              2240 non-null   int64
 14  Gold                2240 non-null   float64
 15  Web                 2240 non-null   int64
 16  Catalog             2240 non-null   int64
 17  Store               2240 non-null   int64
 18  Discount Purchases  2240 non-null   int64
 19  Total Promo         2240 non-null   int64
 20  NumWebVisitsMonth   2240 non-null   int64
 21  cluster             2240 non-null   int64
dtypes: float64(5), int64(17)
memory usage: 385.1 KB

In [11]:
df['cluster'].value_counts()

cluster
2    948
1    704
0    588
Name: count, dtype: int64

In [12]:
x= df.drop(columns='cluster',axis=1)
y = df['cluster']

In [14]:
x.columns

Index(['Age', 'Education', 'Marital Status', 'Parental Status', 'Children',
       'Income', 'Total_Spending', 'Days_as_Customer', 'Recency', 'Wines',
       'Fruits', 'Meat', 'Fish', 'Sweets', 'Gold', 'Web', 'Catalog', 'Store',
       'Discount Purchases', 'Total Promo', 'NumWebVisitsMonth'],
      dtype='object')

In [41]:
# we using bagging techniques 
models = {'Random forest': RandomForestClassifier(),
         'Adaboost classifies':AdaBoostClassifier(),
         'Gradient boosting':GradientBoostingClassifier(),
         'Support vector classifier':SVC(),
         'Logistic Regression':LogisticRegression(),
         'Decision tree classifier':DecisionTreeClassifier(),
         'KNeighbors Classifier':KNeighborsClassifier(),
         'XGB classsifer':XGBClassifier()}

In [42]:
print(list(models))

['Random forest', 'Adaboost classifies', 'Gradient boosting', 'Support vector classifier', 'Logistic Regression', 'Decision tree classifier', 'KNeighbors Classifier', 'XGB classsifer']

In [43]:
def evaluate(x,y,models):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)
    model_list = []
    eval_score_list = []
    for i in range(len(list(models))):
        model = list(models.values())[i]
        model.fit(x_train,y_train)
        y_pred = model.predict(x_test)
        evaluvation_score = accuracy_score(y_pred,y_test)
        model_list.append(model)
        eval_score_list.append(evaluvation_score)
        print(f'-----------score for {list(models.keys())[i]}---------------')
        print(f'the score is {evaluvation_score}')
    print()
    report = pd.DataFrame()
    report['model name'] = model_list
    report['eval score'] = eval_score_list
    return report

In [44]:
report = evaluate(x,y,models)

-----------score for Random forest---------------
the score is 0.953125
-----------score for Adaboost classifies---------------
the score is 0.9486607142857143
-----------score for Gradient boosting---------------
the score is 0.9642857142857143
-----------score for Support vector classifier---------------
the score is 0.765625
-----------score for Logistic Regression---------------
the score is 0.875
-----------score for Decision tree classifier---------------
the score is 0.9419642857142857
-----------score for KNeighbors Classifier---------------
the score is 0.8415178571428571
-----------score for XGB classsifer---------------
the score is 0.9575892857142857

In [45]:
report.sort_values('eval score')

                                          model name  eval score
3                                              SVC()    0.765625
6                             KNeighborsClassifier()    0.841518
4                               LogisticRegression()    0.875000
5                           DecisionTreeClassifier()    0.941964
1  (DecisionTreeClassifier(max_depth=1, random_st...    0.948661
0  (DecisionTreeClassifier(max_features='sqrt', r...    0.953125
7  XGBClassifier(base_score=None, booster=None, c...    0.957589
2  ([DecisionTreeRegressor(criterion='friedman_ms...    0.964286